### ISSUE TITLE
Not all neighbors open when hit empty space

### ISSUE THREAD

**Issue by akatran** [Coni63/Personal_envs_gym#1]
When empty space is revealed not all neighbors cells open.

Imagine the below case where S should be 1, it is currently left untouched by the environment.
+-+-+
|S|1|
+-+-+
|1|0|
+-+-+

while it should be 1
+-+-+
|1|1|
+-+-+
|1|0|
+-+-+

The line of code 
https://github.com/Coni63/Personal_envs_gym/blob/2e7a1e4b72a38459b3b6eb91ed9c112addd99554/minesweeper_env/envs/minesweeper_env.py#L109

could potentially be fixed with 
`                for col_offset, row_offset in [[1, -1], [1, 1], [1, 0], [-1, 0], [-1, -1], [-1, 1], [0, 1], [0, -1]]:`

**Comment by Coni63** [comment]
Thanks for the info. I did not realized that minesweeper also expand along diagonal. Tests and code has been updated with commit #0711b94.
